[project]
name = "example-sqla"
version = "0.1.0"
description = "SQLAlchemy Model Backend Example."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask-admin[sqlalchemy-with-utils,export,translation]",
]

[tool.uv.sources]
flask-admin = { path = "../../", editable = true }
