version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .[all]
sphinx:
  builder: dirhtml
  fail_on_warning: true
