first_names = [
    "Harry",
    "Amelia",
    "Oliver",
    "Jack",
    "Isabella",
    "Charlie",
    "Sophie",
    "Mia",
    "Jacob",
    "Thomas",
    "Emily",
    "Lily",
    "Ava",
    "Isla",
    "Alfie",
    "Olivia",
    "Jessica",
    "Riley",
    "William",
    "James",
    "Geoffrey",
    "Lisa",
    "Benjamin",
    "Stacey",
    "Lucy",
]
last_names = [
    "Brown",
    "Smith",
    "Patel",
    "Jones",
    "Williams",
    "Johnson",
    "Taylor",
    "Thomas",
    "Roberts",
    "Khan",
    "Lewis",
    "Jackson",
    "Clarke",
    "James",
    "Phillips",
    "Wilson",
    "Ali",
    "Mason",
    "Mitchell",
    "Rose",
    "Davis",
    "Davies",
    "Rodriguez",
    "Cox",
    "Alexander",
]
locations = [
    ("Shanghai", "China"),
    ("Istanbul", "Turkey"),
    ("Karachi", "Pakistan"),
    ("Mumbai", "India"),
    ("Moscow", "Russia"),
    ("Sao Paulo", "Brazil"),
    ("Beijing", "China"),
    ("Tianjin", "China"),
    ("Guangzhou", "China"),
    ("Delhi", "India"),
    ("Seoul", "South Korea"),
    ("Shenzhen", "China"),
    ("Jakarta", "Indonesia"),
    ("Tokyo", "Japan"),
    ("Mexico City", "Mexico"),
    ("Kinshasa", "Democratic Republic of the Congo"),
    ("Bangalore", "India"),
    ("New York City", "United States"),
    ("London", "United Kingdom"),
    ("Bangkok", "Thailand"),
    ("Tehran", "Iran"),
    ("Dongguan", "China"),
    ("Lagos", "Nigeria"),
    ("Lima", "Peru"),
    ("Ho Chi Minh City", "Vietnam"),
]
