[project]
name = "example-custom-layout"
version = "0.1.0"
description = "Custom Layout Example."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask-admin[sqlalchemy-with-utils]",
]

[tool.uv.sources]
flask-admin = { path = "../../", editable = true }
